TodoList 구현
rachel-kwak/front-end pull request #8
Opened 2021-05-10 21:08 UTC by rachel-kwak

# To-do List
![image](https://user-images.githubusercontent.com/77603074/117722957-b88cdd80-b21c-11eb-83a4-7fbb541dd29b.png)

<br>

## ⚙️ How to run
```shell
$ cd Practice
$ npm i
$ npm run build    # for webpack
```
### 브라우저 (Chrome)
`public/todo-list.html` 열기

### 테스트
```shell
$ npm run test
```

<br>

## 📋 Specification

* UI는 Todo 입력부와 Todo 목록 출력부, 정보 출력부로 나뉜다.
* Todo는 [완료 전], [완료] 두 가지 상태를 가진다. (default : 완료 전)

### TODO 입력부

* Todo를 입력 받을 수 있는 input 있다.
* Input에 텍스트로 Todo를 입력할 수 있으며, enter키로 Todo를 등록할 수 있다.
* 등록된 Todo는 Todo 목록 상단에 추가되며, 등록과 동시에 input의 내용은 초기화된다.

### TODO 목록 출력부

* 등록된 Todo 목록이 출력된다.
* Todo 는 등록순으로 소팅되어 최근 목록이 상단에 위치한다.
* Todo는 아래와 같이 구성된다.
  * 완료 여부를 나타내는 checkbox
  * 내용을 나타내는 textnode
* checkbox를 클릭하여 완료 처리할 수 있으며, 토클 방식으로 상태를 변경할 수 있다.
  * 체크 : [완료] 상태
  * 체크해제 : [완료 전] default 상태
* 완료된 Todo는 Todo 목록의 하단으로 이동하며, 이미 완료된 Todo를 다시 [완료 전] 상태로 변경하면 Todo 목록 상단으로 다시 이동한다.
  * Todolist의 ul은 하나만 사용한다.
* 완료된 Todo는 취소선과 폰트 컬러로 시각적으로 다르게 한다.

### 하단 정보 출력부
 
* 현재 남아있는 완료 전 Todo의 개수를 출력한다.
* [전체], [완료 전], [완료됨] 의 탭으로 Todo목록을 필터해 볼 수 있는 기능을 제공한다.
* 완료항목 삭제 기능을 제공한다.

2021-05-11 05:13 UTC, js87zz commented on Practice/src/todo-item.js
> +customElements.define('my-todo-item', TodoItem);
커스텀 엘리먼트 사용하지 않고 바닐라로 작성하는게 과제 목표로 알고있는데 확인 부탁드려요~

2021-05-11 05:14 UTC, js87zz commented on Practice/src/todo-item.js
> +    todoItem.setAttribute('class', 'my-todo-item');
속성자체를 class 별도로 할당하는것보다 className이나 classList 를 이용하는게 더 좋을 것 같습니다~!

2021-05-11 05:16 UTC, js87zz commented on Practice/src/todo-item.js
> +    const todoItem = document.createElement('tr');
투두리스트는 테이블과는 다른 형태의 DOM 구조가 되어야할 것 같아요. 표 형태의 데이터를 보여주는 건 아니니까요~이런 구조는 접근성 측면에서도 좋지않으니 참고해주세요~!

2021-05-11 05:21 UTC, jungeun-cho commented
[완료 전], [완료됨] 탭에서 clear completed 하면 괄호 안 숫자가 업데이트 되지 않습니다.

2021-05-11 05:21 UTC, js87zz commented on Practice/src/todo-item.js
> +    check.innerText = '✔︎';
innerText는 원본데이터가 유지되지 않습니다. 의도한게 아니라면 안전성이나 성능 측면에서 textContent를 사용하는게 좋겠네요~!

2021-05-11 05:22 UTC, js87zz commented on Practice/src/todo-item.js
> +    });
블록으로 감싸지 않아도 되겠네요~!

2021-05-11 05:24 UTC, jungeun-cho commented
package.json파일에 build 명령어 webpack으로 작성하는게어떻할까요.
설치된 node_modules path로 잡힙니다.
```json
"build": "webpack"
```

2021-05-11 05:28 UTC, js87zz commented on Practice/src/todo-list.css
> +  outline: none;
아웃라인도 가급적 유지하는게 좋습니다. 강제로 제거하는 것은 키보드로 접근하는 사용자에게 좋지 않으니 참고해주세요~!

2021-05-11 05:29 UTC, js87zz commented on Practice/src/todo-list.css
> +}
속성값이 아니라 클래스로 구분하는게 더 효율적일 것 같아요~

2021-05-11 05:33 UTC, jungeun-cho commented
todolist 인스턴스 두개 생성해서 띄었을 때 출력부가 정상적으로 동작하지 않습니다.
두개의 todolist가 독립적으로 동작해야합니다.

<img width="371" alt="스크린샷 2021-05-11 14 32 05" src="https://user-images.githubusercontent.com/43128697/117763464-d16db100-b265-11eb-92e3-a64a3bc09267.png">

2021-05-11 05:34 UTC, js87zz commented on Practice/src/todo-list.js
> +    text.setAttribute('placeholder', 'What needs to be done?');
인풋 생성은 다른 메서드로 작성하는 게 좋을 것 같고(아래 이벤트 핸들러도 마찬가지입니다). 속성을 추가하는 경우가 많은데 유틸함수 하나 만들어서 여러 속성을 동시에 지정할 수있게 하는것도 좋겠네요~! 근데 type이나 class는 `setAttribute`를 굳이 사용하지 않아도 되겠네요

2021-05-11 05:35 UTC, js87zz commented on Practice/src/todo-list.js
> +      const eventTarget = e.target;
해체 할당은 쓰면안되나요? 혹시 제약이 있나해서요. 없으면 이 문법도 잘 활용하면 좋을 것 같습니다!
`text.addEventListener('keyup', ({ target }) => {...`

2021-05-11 05:36 UTC, js87zz commented on Practice/src/todo-list.js
> +    text.setAttribute('placeholder', 'What needs to be done?');
하나의 메서드에서 너무 많은 책임을 수행하는 것은 코드 가독성이나 향후 의존성관리할때 어려울 수 있으니 항상 고려하는게 좋습니다~! :)

2021-05-11 05:37 UTC, js87zz commented on Practice/src/todo-list.js
> +      this.updateNumbers();
이 이벤트 처리는 메서드로 분리되는게 훨씬 가독성에 좋겠네요. 위에서 이야기한 것과 같은 맥락입니다!

2021-05-11 05:39 UTC, js87zz commented on Practice/src/todo-list.js
> +      if (!eventTarget.value.toString().replace(/ /g, '')) return;
`toString()`은 어떤 용도에서 사용한건가요? 그리고 공백제거는 trim을 사용해도 좋겠네요.

2021-05-11 05:41 UTC, js87zz commented on Practice/src/todo-list.js
> +  createStatusBar() {
이 메서드도 가독성이 너무 떨어지네요 적합하게 분리하고 유틸로 분리할 함수는 분리하는게 좋을 것 같아요. 그리고 공통된 클래스 네임이 많이 보이는데 이런건 프리픽스로 지정해서 사용하는 것도 좋겠네요!
```js
const CLASS_PREFIX = 'my-todo-';

function cls(...names) {
  return names.map((className) => `${CLS_PREFIX}${className}`).join(' ');
}

// ...
left.classList.add(cls('left'));
```

2021-05-11 05:44 UTC, jungeun-cho commented
Active인 상태에서 체크아이콘을 클릭하면 이전에 done처리된 아이템들도 표시됩니다. 확인부탁합니다.

2021-05-11 05:45 UTC, js87zz commented on Practice/src/todo-list.js
> +    left.innerHTML = `<b>${this.todos.length}</b> item(s) left.`;
앞서 말했듯이 이런 DOM관련 로직들은 유틸로 분리해서 필요한 부분은 공통으로 쓰는게 좋겠네요~!

2021-05-11 05:46 UTC, js87zz commented on Practice/src/todo-list.js
> +    active.innerHTML = 'Active';
이런 경우는 innerHTML이 아니라 textContent를 사용하는게 좋겠네요

2021-05-11 05:48 UTC, js87zz commented on Practice/src/todo-list.js
> +    while (this.firstChild.nextSibling.tagName.toLowerCase() === 'my-todo-item') {
nextSibling이 null이면 에러 나겠네요~

2021-05-11 05:48 UTC, rachel-kwak commented on Practice/src/todo-item.js
> +  }
![image](https://user-images.githubusercontent.com/77603074/117764636-cb78cf80-b267-11eb-9d4b-223e6aad7ed4.png)
체크박스에 `checked` 속성처럼 이런 식으로 `completed`만 등록이 됩니다..!

2021-05-11 05:50 UTC, js87zz commented on Practice/src/todo-list.js
> +    while (this.firstChild.nextSibling.tagName.toLowerCase() === 'my-todo-item') {
반복문을 기존 참조를 유지해서 사용하는 경우는 특별한 경우가 아니면 거의 없습니다. 가독성도 떨어지구요. 명확하게 어떤 타겟을 기준으로 하는지 변수에 할당해서 체크하는게 좋을 것 같아요.

2021-05-11 05:53 UTC, js87zz commented on Practice/src/todo-list.js
> +    });
결국 전체 DOM을 다시 그리는 건대 이거는 한번 다른 방법을 생각해보는게 좋을 것 같아요. 데이터 관리만 잘하면 훨씬 간단하게 해결될 것 같네요~!

2021-05-11 05:54 UTC, js87zz commented on Practice/src/todo-list.js
> +    const left = document.querySelector('.my-todo-left');
전체 문서를 대상으로 찾는게 아니라 해당 컴포넌트(뷰)에서 범위를 축소해놓고 찾는게 좋을 것 같아요. 캐쉬해놓고 사용해도 좋구요.

2021-05-11 05:58 UTC, jungeun-cho commented
HTML DOM 구조가 어색합니다.
table 태그안에 입력 박스만 존재하고 나머지는 투두 아이템들은 tr, td로 작성되어있습니다...
<img width="448" alt="스크린샷 2021-05-11 14 55 16" src="https://user-images.githubusercontent.com/43128697/117765509-03ccdd80-b269-11eb-8d22-29e38ed2d7e0.png">

2021-05-11 05:59 UTC, js87zz commented on Practice/src/todo-list.js
> +  filtered(option = '') {
메서드로 보통 과거형을 사용하지 않으니 filter라고 해도 될 것 같아요

2021-05-11 06:01 UTC, js87zz commented on Practice/src/todo-list.js
> +        this.insertBefore(item, currentFirstChild);
어떤 요소가 어디에 들어가는지 이 코드만 보고 바로 이해하기는 좀 어려울 것 같아요. 별도 메서드로 분리하던가 아니면 변수의 네이밍을 더 명확하게 하는게 좋을 것 같아요

2021-05-11 06:03 UTC, jungeun-cho commented on Practice/src/todo-list.js
> +      });
공통으로 사용하는 로직을 재사용할 수 있도록 함수로 분리하여 사용할 수 있을것같아요. 옵션에 따른 배열만 넘겨주어서 계산하도록이요.

2021-05-11 06:06 UTC, js87zz commented on Practice/test/todo-list.test.js
> +    expect(todoList.todos[0]).toEqual(todoItem);
전반적으로 테스트가 다 내부 데이터를 기준으로 검증하고 있는대요. 이런 테스트는 결과적으로 깨지기 쉽습니다. 내부 인스턴스 변수나 구조가 바뀌면 모두 깨질테니까요. 이벤트가 발생했을때 결과적으로 **DOM**이 어떻게 변경되었는지를 검증하는게 좋을 것 같습니다.

2021-05-11 06:10 UTC, js87zz approved these changes
리뷰 완료했습니다. 고생하셨어요~

2021-05-11 06:12 UTC, jungeun-cho requested changes
UI가 예쁘네요~ 수고하셨습니다. :)

- 기본적인 동작에서 버그가 발견되어 리포트했습니다.
- DOM구조가 어색한 경향이 있어요. 예를 들어 table을 사용하였다면 table태그 내에 tr, td 요소들이 있어야할 것같아요. 리스트 아이템이라 여기서는 ul, li를 사용해도 좋을것 같습니다.
- class를 다룰 땐 setAttribute, getAttribute보다는 className나 classList를 사용해서 클래스명들을 조작하는게 더 좋을것같습니다. setAttribute로 사용할 때 여러개의 클래스 명을 넣어줘야하는 경우 공백으로 구분하여 넣어주었는데 가독성이 떨어질 수 있습니다.
- `my-todo-list`는 독립적으로 동작해야합니다. 여러개의 인스턴스를 생성하였을 경우 오류가 발생합니다. 확인부탁합니다.

2021-05-11 06:17 UTC, rachel-kwak commented on Practice/src/todo-item.js
> +    const todoItem = document.createElement('tr');
앗.. 표 형태의 모양이라고 생각했는데.. ㅠㅠ
전반적으로 모두 수정해야겠네요 😂

2021-05-11 09:22 UTC, Vnthf reviewed
수고하셨어요.

2021-05-11 16:48 UTC, rachel-kwak commented on Practice/public/todo-list.html
> +    <my-todo-list style="width: 350px;"></my-todo-list>
`my-todo-list`는 `min-width`가 걸려있고 width가 없는 경우 100% 공간을 차지하게 됩니다..!! 너비는 사용자가 커스텀할 부분이라고 생각해서 저렇게 해두었습니다.

2021-05-13 19:40 UTC, dotaitch reviewed
늦었지만.. 리뷰 완료합니다. 고생하셨습니다~

* Active, Complete 탭에서 체크/언체크 시 동작이 이상합니다.
* eslint가 작동하지 않네요. tooltip 리뷰 때 알려준 문제와 동일합니다. 이것도 수정 부탁드려요!

2021-05-13 19:59 UTC, dotaitch commented on Practice/src/todo-item.js
> +    check.addEventListener('click', () => {
부분은 이벤트 위임을 사용해서 처리해도 좋을 것 같네요. 
투두 항목이 많아지면 그만큼 이벤트 리스너도 많아지고 성능 상 이슈도 생길 수 있어요.

2021-05-15 11:26 UTC, rachel-kwak commented on Practice/src/todo-list.css
> +  outline: none;
구현 예시 이미지?가 있었는데 거기에 아웃라인이 없었어서.. ㅎㅎ.. ㅠ_ㅠ 밑줄이 보이도록 수정하겠습니다!

2021-05-15 21:37 UTC, rachel-kwak commented on Practice/src/todo-item.js
> +customElements.define('my-todo-item', TodoItem);
몰랐습니다 ㅠ_ㅠ.. `customElements` 사용하지 않는 것으로 수정했습니다!

2021-05-15 21:38 UTC, rachel-kwak commented on Practice/src/todo-list.css
> +  outline: none;
구현 예시 이미지?가 있었는데 거기에 아웃라인이 없었어서.. ㅎㅎ.. 😅

2021-05-15 21:40 UTC, rachel-kwak commented on Practice/src/todo-list.css
> +  display: inline-block;
flex를 나중에 추가했는데 추가하면서 안 지운 것 같습니다.. ㅎㅎ

2021-05-15 21:41 UTC, rachel-kwak commented on Practice/src/todo-list.js
> +      if (!eventTarget.value.toString().replace(/ /g, '')) return;
`toString()`을.. 왜 썼을까요..?
`replace()`도 `trim()` 사용하는 걸로 바꿨습니다.. :)

2021-05-15 21:42 UTC, rachel-kwak commented on Practice/src/todo-list.js
> +    while (this.firstChild.nextSibling.tagName.toLowerCase() === 'my-todo-item') {
구조가 완전히 변경되어서 해당 부분은 더이상 사용하지 않습니다..!!

2021-05-15 21:43 UTC, rachel-kwak commented on Practice/src/todo-list.js
> +    });
다시 정렬하지 않고 list를 todo 부분과 done 부분으로 나눠서 todo는 prepend만 하고 done은 append만 하는 걸로 바꿨습니다!! :D

2021-05-15 21:43 UTC, rachel-kwak commented on Practice/src/todo-list.js
> +  filtered(option = '') {
수정하면서 해당 메서드는 사용하지 않지만 `filteredBy` ... 였는데 By를 지운 것 같네요 ㅎㅎ..

2021-05-15 21:44 UTC, rachel-kwak commented on Practice/src/todo-list.js
> +    const clear = document.querySelector('.my-todo-clear');
별개로 동작하도록 수정했습니다 :)

2021-05-15 21:45 UTC, rachel-kwak commented on Practice/test/todo-list.test.js
> +    expect(todoList.todos[0]).toEqual(todoItem);
DOM에서 찾는 걸로 수정했습니다!!

2021-05-15 21:49 UTC, rachel-kwak commented on Practice/src/todo-item.js
> +    text.innerText = content;
헤더, 리스트, 상태바 세가지로 분리했습니다!

2021-05-17 18:25 UTC, rachel-kwak commented on Practice/src/todo-list.js
> +    clear.innerHTML = `Clear completed (<b>${this.dones.length}</b>)`;
`<b>` 태그만 가져와서 숫자만 바꾸도록 수정했습니다!

2021-05-17 18:33 UTC, rachel-kwak commented on Practice/src/todo-list.js
> +      const eventTarget = e.target;
아하 저렇게도 사용할 수 있군요! 참고하겠습니다 :D

2021-05-21 05:57 UTC, merged